FROM ubuntu:16.04

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y make g++ gcc git tree cmake cmake-curses-gui nano pkg-config
RUN apt-get install -y libboost-chrono-dev libboost-date-time-dev libboost-filesystem-dev libboost-system-dev libboost-thread-dev libusb-1.0-0-dev libudev-dev libcereal-dev libeigen3-dev libv4l-dev
